baseURL = "https://thecyberacademic.com/"
languageCode = "en-us"
title = "The Cyber Academic Podcast"
theme = "hugo-ink"
paginate = 5

copyright = "Copyright © The Cyber Academic"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	subtitle = "A podcast by [Dr Ahmed Ibrahim](https://ahmedibrahim.net). Find and listen to the episodes in your favourite podcast apps."

	# Optional 64x64 avatar image.
	avatar = "avatar.png"

	# Content types to disable Disqus on.
	#disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ai8rahim"


[[params.social]]
name = "RSS"
icon = "rss"
url = "https://feed.podbean.com/thecyberacademic/feed.xml"


[taxonomies]
   tag = "tags"
